ai-gpgpu14
USED GPUs: 0,1
/home/23r8105_messou/lab/time_series_augmentation_mix
/var/spool/slurm-llnl/slurmd/job02189/slurm_script: line 8: activate: No such file or directory
Error: The script directory (/var/spool/slurm-llnl/slurmd/job02189) does not contain '/time_series_augmentation_mix'. Using the default directory.
Configuration:
  GPUS: 2
  MODEL: cnn_attention_bigru
  OPTIMIZER: adam
  INTERPRET_METHOD: lime
  INTERPRET: false
  NORMALIZE_INPUT: true
  TRAIN: false
  TUNE: true
  SAVE: true
  gnome_data: ELECTRICITY_GLOBAL_REACTIVE_POWER HOTWATER_FOX_LODGING_ALANA SOLAR_BOBCAT_EDUCATION_ALISSA SOLAR_BOBCAT_EDUCATION_COLEMAN WATER_PANTHER_LODGING_CORA WATER_WOLF_EDUCATION_URSULA GAS_PANTHER_LODGING_DEAN
  aug_tech_mix: sequential_combined4 sequential_combined5 sequential_combined7 sequential_combined12
Running dataset: ELECTRICITY_GLOBAL_REACTIVE_POWER, augmentation: sequential_combined4, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=ELECTRICITY_GLOBAL_REACTIVE_POWER --preset_files --augmentation_method=sequential_combined4 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:34:36,303] A new study created in memory with name: no-name-552dfe02-a0bc-4076-a080-35ec0182971a
[I 2024-11-08 22:34:36,306] Trial 0 pruned. 
Applying augmentation method: sequential_combined4
x_temp.shape: (747, 14, 1), y_temp.shape: (747,)
x_aug.shape: (1494, 14, 1), y_aug.shape: (1494,)
Augmentation done: ads_sequential_combined4
Augmentation process took 182.20 ms
x_train shape after augmentation: (1494, 14, 1), y_train shape after augmentation: (1494,)
Starting hyperparameter tuning...
Trial 0 failed with exception: embed_dim must be divisible by num_heads
Traceback (most recent call last):
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/main.py", line 39, in <module>
    tuner.tune_hyperparameters(n_trials=1)  # 1 for test
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/models/tuning.py", line 431, in tune_hyperparameters
    best_params = study.best_trial.user_attrs["params"]
                  ^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/study/study.py", line 157, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/storages/_in_memory.py", line 234, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
Running dataset: ELECTRICITY_GLOBAL_REACTIVE_POWER, augmentation: sequential_combined5, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=ELECTRICITY_GLOBAL_REACTIVE_POWER --preset_files --augmentation_method=sequential_combined5 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:34:54,469] A new study created in memory with name: no-name-a0ceabbb-3efa-4c00-931c-dd15a05032d8
[I 2024-11-08 22:34:54,473] Trial 0 pruned. 
Applying augmentation method: sequential_combined5
x_temp.shape: (747, 14, 1), y_temp.shape: (747,)
x_aug.shape: (1494, 14, 1), y_aug.shape: (1494,)
Augmentation done: ads_sequential_combined5
Augmentation process took 42.44 ms
x_train shape after augmentation: (1494, 14, 1), y_train shape after augmentation: (1494,)
Starting hyperparameter tuning...
Trial 0 failed with exception: embed_dim must be divisible by num_heads
Traceback (most recent call last):
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/main.py", line 39, in <module>
    tuner.tune_hyperparameters(n_trials=1)  # 1 for test
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/models/tuning.py", line 431, in tune_hyperparameters
    best_params = study.best_trial.user_attrs["params"]
                  ^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/study/study.py", line 157, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/storages/_in_memory.py", line 234, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
Running dataset: ELECTRICITY_GLOBAL_REACTIVE_POWER, augmentation: sequential_combined7, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=ELECTRICITY_GLOBAL_REACTIVE_POWER --preset_files --augmentation_method=sequential_combined7 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:35:12,327] A new study created in memory with name: no-name-5193733e-b599-49bc-9594-3ccd8cecc315
[I 2024-11-08 22:35:12,330] Trial 0 pruned. 
Applying augmentation method: sequential_combined7
x_temp.shape: (747, 14, 1), y_temp.shape: (747,)
x_aug.shape: (1494, 14, 1), y_aug.shape: (1494,)
Augmentation done: ads_sequential_combined7
Augmentation process took 40.92 ms
x_train shape after augmentation: (1494, 14, 1), y_train shape after augmentation: (1494,)
Starting hyperparameter tuning...
Trial 0 failed with exception: embed_dim must be divisible by num_heads
Traceback (most recent call last):
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/main.py", line 39, in <module>
    tuner.tune_hyperparameters(n_trials=1)  # 1 for test
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/models/tuning.py", line 431, in tune_hyperparameters
    best_params = study.best_trial.user_attrs["params"]
                  ^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/study/study.py", line 157, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/storages/_in_memory.py", line 234, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
Running dataset: ELECTRICITY_GLOBAL_REACTIVE_POWER, augmentation: sequential_combined12, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=ELECTRICITY_GLOBAL_REACTIVE_POWER --preset_files --augmentation_method=sequential_combined12 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:35:30,660] A new study created in memory with name: no-name-bfb6b9cf-d2ff-48f7-8449-158fcc4f457c
[I 2024-11-08 22:35:36,200] Trial 0 pruned. 
Applying augmentation method: sequential_combined12
x_temp.shape: (747, 14, 1), y_temp.shape: (747,)
x_aug.shape: (1494, 14, 1), y_aug.shape: (1494,)
Augmentation done: ads_sequential_combined12
Augmentation process took 132.06 ms
x_train shape after augmentation: (1494, 14, 1), y_train shape after augmentation: (1494,)
Starting hyperparameter tuning...
Trial 0 failed with exception: input.size(-1) must be equal to input_size. Expected 128, got 512
Traceback (most recent call last):
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/main.py", line 39, in <module>
    tuner.tune_hyperparameters(n_trials=1)  # 1 for test
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/models/tuning.py", line 431, in tune_hyperparameters
    best_params = study.best_trial.user_attrs["params"]
                  ^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/study/study.py", line 157, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/storages/_in_memory.py", line 234, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
Running dataset: HOTWATER_FOX_LODGING_ALANA, augmentation: sequential_combined4, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=HOTWATER_FOX_LODGING_ALANA --preset_files --augmentation_method=sequential_combined4 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:35:54,775] A new study created in memory with name: no-name-293f5b88-3523-4f7e-9fe5-ef67ac384fde
[I 2024-11-08 22:35:54,779] Trial 0 pruned. 
Applying augmentation method: sequential_combined4
x_temp.shape: (366, 15, 1), y_temp.shape: (366,)
x_aug.shape: (732, 15, 1), y_aug.shape: (732,)
Augmentation done: ads_sequential_combined4
Augmentation process took 97.06 ms
x_train shape after augmentation: (732, 15, 1), y_train shape after augmentation: (732,)
Starting hyperparameter tuning...
Trial 0 failed with exception: embed_dim must be divisible by num_heads
Traceback (most recent call last):
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/main.py", line 39, in <module>
    tuner.tune_hyperparameters(n_trials=args.n_trials)  # 1 for test
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/lab/time_series_augmentation_mix/models/tuning.py", line 431, in tune_hyperparameters
    best_params = study.best_trial.user_attrs["params"]
                  ^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/study/study.py", line 157, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/23r8105_messou/anaconda3/envs/time_series_augmix/lib/python3.12/site-packages/optuna/storages/_in_memory.py", line 234, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
Running dataset: HOTWATER_FOX_LODGING_ALANA, augmentation: sequential_combined5, ratio: 1
Executing: python3 main.py --gpus=2 --dataset=HOTWATER_FOX_LODGING_ALANA --preset_files --augmentation_method=sequential_combined5 --augmentation_ratio=1 --optimizer=adam --model=cnn_attention_bigru --interpret --interpret_method=lime --normalize_input --tune --save
[I 2024-11-08 22:36:11,046] A new study created in memory with name: no-name-46b00594-fee6-47b0-8e02-3e27579d2fc7
slurmstepd-ai-gpgpu14: error: *** JOB 2189 ON ai-gpgpu14 CANCELLED AT 2024-11-08T22:36:48 ***
